version: "3.6"
services:
    db:
        container_name: postgres-db
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=root
            - POSTGRES_DB=sph-flutter
        ports:
            - "5432:5432"
        volumes:
            - ./docker/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
